### ISSUE TITLE
Logrotate config for nginx

### ISSUE THREAD

**Issue by coderholic** [GoogleCloudPlatform/appengine-sidecars-docker#124]
A logrotate config file for nginx is included here: https://github.com/GoogleCloudPlatform/appengine-sidecars-docker/blob/master/nginx_proxy/Dockerfile#L30 - but from what I can tell logrotated isn't installed in the sidecar images, and this doesn't actually do anything. There's a separate logrotate config for nginx files that's configured on the host machine.

**Comment by yanweiguo** [comment]
Yes, we have logrotate config for nginx on the host machine.
