### ISSUE TITLE
Proxy settings for websockets 

### ISSUE THREAD

**Issue by MarkEdmondson1234** [GoogleCloudPlatform/appengine-sidecars-docker#48]
Hi, not sure this is monitored but giving it a go :)

I'm trying to deploy Shiny Docker applications through Google app Engine via flexible containers.

The [documentation for Shiny Server](https://support.rstudio.com/hc/en-us/articles/213733868-Running-Shiny-Server-with-a-Proxy) states it requires these proxy settings to enable websockets to work:

```
http {

  map $http_upgrade $connection_upgrade {
      default upgrade;
      ''      close;
    }

  server {
    listen 80;
   
    location / {
      proxy_pass http://localhost:3838;
      proxy_redirect http://localhost:3838/ $scheme://$host/;
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection $connection_upgrade;
      proxy_read_timeout 20d;
    }
  }
}
```

The lines in particular are missing from this Docker file that I see is used in the flexible VM during debugging:

```
  proxy_set_header Upgrade $http_upgrade;
  proxy_set_header Connection $connection_upgrade;
```

An example application which displays the errors in the web console is here:
https://mark-edmondson-usa.appspot.com/sample-apps/hello/

The app engine files I'm deploying are here:
https://github.com/MarkEdmondson1234/appengine-shiny

**Comment by drewinglis** [comment]
Hi Mark, I'm sorry we let this issue go for so long. Websockets doesn't work on Flex right now, but we're working on adding support. Can you send me an email if you'd like us to get in touch when we're looking for testers? My @google.com email is the same as my GitHub username. Thanks!
