### ISSUE TITLE
Logging X-Forwarded-For in jsonPayload

### ISSUE THREAD

**Issue by iamacarpet** [GoogleCloudPlatform/appengine-sidecars-docker#59]
Hello,

Would you be willing to accept a change in nginx_proxy and fluentd_logger to log the X-Forwarded-For header into the jsonPayload?

Currently when using a reverse proxy like Cloudflare, only their IP is logged and some compliance schemes require the real visitor IP to be logged.

To avoid having to parse/transform the X-Forwarded-For header which would require different config for every setup, the original ticket requesting this for App Engine Standard suggested just logging the header in it's raw form, which would be enough to manually determine the visitor IP if eventually required for an audit.

Regards,
iamacarpet

**Comment by drewinglis** [comment]
Hello iamacarpet, I'm sorry we let this go for so long without responding. Yes, we would be willing to accept such a pull request, please feel free to follow up with one. :)

**Comment by drewinglis** [comment]
I'm going to close this for now, but please feel free to reopen with a pull request if you want.
